### ISSUE TITLE
Error getting node information

### ISSUE THREAD

**Issue by jrosen** [shlomoswidler/tabula_rasa#10]
I may be using this wrong. But I tried using this so I can use the 'apache2' cookbook in Opsworks.  I'm using the stock Ubuntu 14.04.  I included 'tabula_rasa' in the setup step, and it worked fine (I didn't have anything in the setup step in the tabula_rasa configs, but I also included it in the configure step, where all of my build was happening. It looked to be working fine, but I got the following error, right in the beginning of the build: 

```
[2015-08-17T23:02:15+00:00] INFO: Starting Chef Run for webserver1.localdomain
[2015-08-17T23:02:15+00:00] INFO: Running start handlers
[2015-08-17T23:02:15+00:00] INFO: Start handlers complete.
[2015-08-17T23:02:15+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: /reports/nodes/webserver1.localdomain/runs
[2015-08-17T23:02:23+00:00] ERROR: #<Encoding::InvalidByteSequenceError: "\xE2" on US-ASCII>
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/cookbook/metadata.rb:444:in `encode'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/cookbook/metadata.rb:444:in `to_json'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/cookbook/metadata.rb:444:in `to_json'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/json-1.7.7/lib/json/common.rb:285:in `generate'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/json-1.7.7/lib/json/common.rb:285:in `pretty_generate'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:102:in `block in get'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:339:in `with_entry'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:82:in `get'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_base.rb:42:in `get_data'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:77:in `block in depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_base.rb:29:in `call'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_router.rb:23:in `call'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/server.rb:335:in `block in make_app'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:412:in `call'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:412:in `handle_request'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:306:in `process_client'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:215:in `block in run'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `call'
/opt/aws/opsworks/releases/20150727112318_3425-20150727112318/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `block in spawn_thread'
[2015-08-17T23:02:23+00:00] INFO: HTTP Request Returned 500 Internal Server Error: 

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================


Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.


```

**Comment by shlomoswidler** [comment]
Looks like a Unicode character issue in one of the cookbooks you're pulling in. See these two threads for more info, there are several ways to resolve this.
https://forums.aws.amazon.com/thread.jspa?threadID=149423
https://github.com/berkshelf/berkshelf-api/issues/112
