### ISSUE TITLE
Error executing action `install` on resource 'chef_gem[pg]'

### ISSUE THREAD

**Issue by gayan** [shlomoswidler/tabula_rasa#6]
Has anyone had this happen to them using tabula_rasa?
# 
# Error executing action `install` on resource 'chef_gem[pg]'
## Bundler::GemfileNotFound

Could not locate Gemfile
## Cookbook Trace:

/home/tabula-rasa/cache/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'
/home/tabula-rasa/cache/cookbooks/postgresql/recipes/ruby.rb:21:in`from_file'
/home/tabula-rasa/cache/cookbooks/postgres-install/recipes/default.rb:8:in `from_file'
## Resource Declaration:
# In /home/tabula-rasa/cache/cookbooks/postgresql/recipes/ruby.rb

55:     chef_gem "pg"
56:   rescue Gem::Installer::ExtensionBuildError, Mixlib::ShellOut::ShellCommandFailed => e
## Compiled Resource:
# Declared in /home/tabula-rasa/cache/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'

chef_gem("pg") do
provider Chef::Provider::Package::Rubygems
action :install
retries 0
retry_delay 2
package_name "pg"
version "0.17.1"
cookbook_name "postgresql"
recipe_name "ruby"
end

**Comment by shlomoswidler** [comment]
I've been looking into this on and off for the past month, and I am sorry to say that I am no closer to understanding the cause of this.

**Comment by nickjwebb** [comment]
I've hit this bug, but with `chef_gem[ruby-augeas]` 

```
[2015-05-31T21:01:32+00:00] INFO: Processing chef_gem[ruby-augeas] action install (augeas::geminstall line 10)
 
================================================================================
Error executing action `install` on resource 'chef_gem[ruby-augeas]'
================================================================================
 
 
Bundler::GemfileNotFound
------------------------
Could not locate Gemfile
 
 
Cookbook Trace:
---------------
/home/tabula-rasa/cache/cookbooks/augeas/recipes/geminstall.rb:10:in `from_file'
/home/tabula-rasa/cache/cookbooks/bamboo-agent/recipes/default.rb:32:in `from_file'
/home/tabula-rasa/cache/cookbooks/tile-web/recipes/default.rb:12:in `from_file'
 
 
Resource Declaration:
---------------------
# In /home/tabula-rasa/cache/cookbooks/augeas/recipes/geminstall.rb
 
10: chef_gem 'ruby-augeas' do
11:   action :install
12: end
 
 
 
Compiled Resource:
------------------
# Declared in /home/tabula-rasa/cache/cookbooks/augeas/recipes/geminstall.rb:10:in `from_file'
 
chef_gem("ruby-augeas") do
provider Chef::Provider::Package::Rubygems
action [:install]
retries 0
retry_delay 2
package_name "ruby-augeas"
version "0.5.0"
cookbook_name "augeas"
recipe_name "geminstall"
end
 
 
 
 
================================================================================
Recipe Compile Error in /home/tabula-rasa/cache/cookbooks/tile-web/recipes/default.rb
================================================================================
 
 
Bundler::GemfileNotFound
------------------------
chef_gem[ruby-augeas] (augeas::geminstall line 10) had an error: Bundler::GemfileNotFound: Could not locate Gemfile
```

I'm not super hopeful of my ability to fix this, but I will look.

**Comment by nickjwebb** [comment]
Hi @shlomoswidler ,

Could you allow access to https://s3.amazonaws.com/shlomo-test/tabula-rasa-issue-6-test.tar.gz once more, it's giving me a 403 Forbidden right now.

Nick

**Comment by shlomoswidler** [comment]
@nickjwebb OK, it is now public readable.

**Comment by nickjwebb** [comment]
Thanks @shlomoswidler we are actively trying to fix this issue... unfortunately nothing yet, but I do have a chef export working with me.

**Comment by nickjwebb** [comment]
A little bit of progress to report here. Reproducing this in a controlled environment without a lot of distracting variables has been an exercise in patience for me.

I do not have a solution, but I can refine the problem statement.

It appears that using `chef_gem` within tabula rasa installs the gems in a place not accessible to OpsWorks chef. If you use the same gem (including specific version) in tabula_rasa that has already been installed by OpsWorks, it works.

In my test case I needed to use the `s3_file` cookbook, which depends on the `rest-client` gem. By default it uses the latest version (1.7.x), but OpsWorks already has version 1.6.7 installed and working. If I simply override the `s3_file` "version" attribute, it functions properly. Here is my custom JSON (note that the repo is public):

```
{ 
  "tabula_rasa" : {
    "scm": {
      "type": "git",
      "repository": "git@github.com:nickjwebb/tabula-rasa-test.git"
    },
    "recipes" : { 
      "setup": [ "tabula-rasa-test::breaks" ] 
    }
  },
  "s3_file" : {
    "rest-client" : {
       "version" : "1.6.7"
    }
  }
}
```

Here is the very simple `tabula-rasa-test::breaks` recipe (subject to change):

```
# Grab custom postgres package & install
s3_file "/tmp/phpunit-4.6.9.phar" do
  remote_path "/phpunit-4.6.9.phar"
  bucket "packages.rwsnw.com"
  s3_url "https://s3-us-west-2.amazonaws.com/packages.rwsnw.com"
  owner "root"
  group "root"
  mode "0644"
end
```

Probably impractical, but one could in theory include a recipe to install all the gems needed (via `chef_gem`) in a recipe "outside" of tabula_rasa as a workaround.

**Comment by hashwrapi** [comment]
@gayan @tarky @shlomoswidler @mfdii @nickjwebb Guys, can you tell me how can we lock pg version?
`chef_gem[pg]
`as per above error it is trying to compile version "0.17.1" but if we check this link so in which file we have to edit to lock pg version?
Link is here as above https://s3.amazonaws.com/shlomo-test/tabula-rasa-issue-6-test.tar.gz
